#:import MDTopAppBar kivymd.uix.toolbar
#:import Window kivy.core.window.Window
#:import NoTransition kivy.uix.screenmanager.NoTransition

#:import StatusBar ui.widgets.status_bar.StatusBar
#:import HomeScreen ui.screens.home_screen.HomeScreen
#:import ScanScreen ui.screens.scan_screen.ScanScreen
#:import TrackingScreen ui.screens.tracking_screen.TrackingScreen
#:import ProfilScreen ui.screens.profil_screen.ProfilScreen
#:import ControlMenuScreen ui.screens.control_menu_screen.ControlMenuScreen
#:import HeadsetScreen ui.screens.headset_screen.HeadsetScreen
#:import PilotageScreen ui.screens.pilotage_screen.PilotageScreen
#:import GameScreen ui.screens.game_screen.GameScreen

BoxLayout:
    orientation: "vertical"

    canvas.before:
        Color:
            rgba: (0.941, 0.941, 0.953, 1)
        Rectangle:
            pos: self.pos
            size: self.size

    # ---------- TOP BAR ----------
    MDTopAppBar:
        id: top_bar
        title: "Accueil"
        md_bg_color: app.theme_cls.primary_color
        left_action_items: [["account-circle", lambda x: print(x)]]
        right_action_items: [["", lambda x: print(x)]]
    
    # -------- SUIVI BLE / Wi-Fi / FC ------
    StatusBar:
        id: status_bar

    # ---------- SCREEN MANAGER ----------
    ScreenManager:
        id: screen_manager
        transition: NoTransition()

        HomeScreen: 
            name: "home"
        
        ScanScreen:
            name: "scan"
        
        TrackingScreen:
            name: "tracking"
        
        ProfilScreen:
            name: "profil"

        ControlMenuScreen:
            name: "control_menu"

        HeadsetScreen:
            name: "headset"

        PilotageScreen:
            name: "pilotage"

        # GameScreen:
        #     name: "game"

    # ---------- BOTTOM NAVIGATION (FIXE) ----------
    MDBottomNavigation:
        id: bottom_nav
        size_hint_y: None
        height: dp(81)
        use_text: Window.width >= dp(600)
        transition: NoTransition
		
        MDBottomNavigationItem:
            name: "home_tab"
            text: "Home"
            icon: "home"
            on_tab_press:
                # screen_manager.current = "home"
                # top_bar.title = "Home"
                app.change_screen("home", "Home")

        MDBottomNavigationItem:
            name: "scan_tab"
            text: "Sensor"
            icon: "bluetooth"
            on_tab_press:
                # screen_manager.current = "scan"
                # top_bar.title = "Sensor Connection"
                app.change_screen("scan", "Sensor Connection")

        MDBottomNavigationItem:
            name: "tracking_tab"
            text: "HR Tracking"
            icon: "chart-line"
            on_tab_press:
                # screen_manager.current = "tracking"
                # top_bar.title = "Heart Rate Tracking"
                app.change_screen("tracking", "Heart Rate Tracking")

        MDBottomNavigationItem:
            name: "pilotage_tab"
            text: "Control"
            icon: "microsoft-xbox-controller-menu"
            on_tab_press:
                app.change_screen("control_menu", "Contrôle")
        
        # MDBottomNavigationItem:
        #     name: "game_tab"
        #     text: "Game Screen"
        #     icon: "fit-to-screen-outline"
        #     on_tab_press:
        #         screen_manager.current = "game"
        #         top_bar.title = "Game Screen"

