#:import platform kivy.utils.platform

#:set GREEN_BG (0.906, 0.961, 0.914, 1)
#:set GREEN_FG (0.176, 0.490, 0.196, 1)
#:set RED_BG (0.988, 0.910, 0.906, 1)
#:set RED_FG (0.776, 0.157, 0.157, 1)
#:set AMBER_BG (1, 0.976, 0.882, 1)
#:set AMBER_FG (0.780, 0.518, 0.047, 1)
#:set GRAY_BG (0.925, 0.925, 0.925, 1)
#:set GRAY_FG (0.459, 0.459, 0.459, 1)

<StatusBar>:
    orientation: "horizontal"
    padding: [0, dp(50), dp(20), dp(50)]
    spacing: dp(10)
    size_hint_y: None
    height: dp(30)

    Widget:  # pousse les icônes à droite

    MDIcon:
        id: ble_icon
        icon: "bluetooth" if root.ble_connected else "bluetooth-off"
        theme_text_color: "Custom"
        text_color: GREEN_FG if root.ble_connected else (1, 0, 0, 1)
        opacity: 0 if platform == "win" else 1
        disabled: True if platform == "win" else False

    MDIcon:
        id: wifi_icon
        icon: "wifi" if root.wifi_connected else "wifi-off"
        theme_text_color: "Custom"
        text_color: GREEN_FG if root.wifi_connected else (1, 0, 0, 1)

    MDIcon:
        id: hr_icon
        icon: "heart" if root.hr_sensor_connected else "heart-off"
        theme_text_color: "Custom"
        text_color: root.hr_icon_color
    
    MDIcon:
        id: unity_icon
        icon: "unity" if root.unity_connected else "lan-disconnect"
        theme_text_color: "Custom"
        text_color: GREEN_FG if root.unity_connected else (1, 0, 0, 1)
